name: Custom Action
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "run hello world"
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action
