name: Github Action Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
      - run: List files in the repository
      - run: |
          ls -la ${{github.workspace}}
