name: Github Action Demo

on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
      - name: Check the repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls -la ${{github.workspace}}
  Test-Another-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from another job"
  Check-Bats-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
      - run: sudo npm i -g bats
      - run: bats -v
