name: Test Workflow

on: [push]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{toJSON(job)}}
        run: echo "$JOB_CONTEXT"
  Test-Workflow:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - run: echo "Hello World"
